### ISSUE TITLE
.leave mode [chars:tp:selfhurt:quit]

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst-Client-Bugs#10]
#### Description of the Bug
When I type `.leave mode chars` this happens:
![screen shot 2016-05-02 at 16 24 23](https://cloud.githubusercontent.com/assets/11584045/14955437/9bf0ffa8-1082-11e6-86f1-c2ac9820014e.png)

I can't give you bug report due to: #11

#### How to Reproduce the Bug
Type `.leave mode chars` other than chars, also tp, selfhurt and quit opens the bug window too.

#### Other Information
- Wurst Client version: 3.0
- Operating system: Mac OS 10.11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThisTestUser** [comment]
The setMode() function is trying to get modesetting(1), which does not exist.
There is also another bug where setting the leave mode in singleplayer does not work. You can fix this by making the error message popup only if the length of the command is not 2 (.leave mode chars).

**Comment by mcccs** [comment]
> There is also another bug where setting the leave mode in singleplayer does not work. You can fix this by making the error message popup only if the length of the command is not 2 (.leave mode chars).

Are you sure? Before `Cannot leave server when in singleplayer.` added, It used to crash.

**Comment by ThisTestUser** [comment]
Its not disconnecting but setting the mode. It won't crash.
