### ISSUE TITLE
Cant place a command block in a creative servers..

### ISSUE THREAD

**Issue by noammiz007** [Wurst-Imperium/Wurst-Client-Bugs#100]
#### Description of the Bug
i am playing in alot of creative servers and i cant even put a cmd block there. is not saying "the server have no command block enabled" is just not letting me to put it..

#### How to Reproduce the Bug
go to any creative server with plotme plugin and put there a cmd-block that you get from the hack

#### Other Information
- Wurst Client version: v3.4
- Operating system: Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

---

**Comment by qbus2002** [comment]
I'ts blocked by the server.......
