### ISSUE TITLE
Items bug

### ISSUE THREAD

**Issue by Adamjoko** [Wurst-Imperium/Wurst-Client-Bugs#102]
#### Description of the Bug
Everytime I drop a item it looks like stone until I pick it up.

#### How to Reproduce the Bug
just drop the item

#### Other Information
- Wurst Client version: 3.4
- Operating system: none

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by qbus2002** [comment]
Ehmm you say operating system none...
Try use no resourcepacks beacose or use windows 10
Beacose this bug don't happen to me
