### ISSUE TITLE
commandblock's

### ISSUE THREAD

**Issue by qbus2002** [Wurst-Imperium/Wurst-Client-Bugs#105]
#### Description of the Bug
I can't open command block's and when you place it there's no animation and no destruct animation

#### How to Reproduce the Bug
go on your server or your save and place an commandblock then try to open it
#### Other Information
- newest 3.4 (mc 1.9)
- Windows 10 Proffesional

**Comment by mcccs** [comment]
Does it work on nonmodded mc?

**Comment by qbus2002** [comment]
Yep my frien does also have same problem

**Comment by qbus2002** [comment]
Man in server propeties is it on and i have op and gamemode creative 
There is also no animation for placing and destroying
First check for youreself of you have same issuse and then ask for server problems beacose it even does'nt work while i'm on my own save with cheats on and gamemode (yes i tried open to lan and allow cheats)

**Comment by qbus2002** [comment]
ok reinstalled mc and windows helped :D
