### ISSUE TITLE
ummm whenever i click left control my gui doesn't show up on my screen so i basically can't use wolfram at all

### ISSUE THREAD

**Issue by MLGHomieDuck** [Wurst-Imperium/Wurst-Client-Bugs#106]
#### Description of the Bug
Replace this text with a description of the bug that you are reporting. What did you expect to happen? What happened instead?

#### How to Reproduce the Bug
Replace this text with a list of the necessary steps to reproduce the bug. What does one need to do in order for this bug to occur?

#### Other Information
- Wurst Client version: 
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by qbus2002** [comment]
Ummm you don't used template but try delete wurst folder it's .minecraft/wurst

**Comment by Stego27** [comment]
I think your on the bug tracker for the wrong client
