### ISSUE TITLE
GUI Bug

### ISSUE THREAD

**Issue by MLGHomieDuck** [Wurst-Imperium/Wurst-Client-Bugs#107]
#### Description of the Bug
When I clicked left control my gui didn't pop up on my screen, so I basically cant use wurst

#### Other Information
- Wurst Client version: Wurst v3.4
- Operating system: Windows 10    XD

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
## Duplicate https://github.com/Wurst-Imperium/Wurst-Client-Bugs/issues/33#issuecomment-219439876

**Comment by qbus2002** [comment]
You can delete your wurst  folder in .minecraft
