### ISSUE TITLE
My regen doesn't work for wurst 1.9x or wurst v3.4

### ISSUE THREAD

**Issue by ProPandaAssasin** [Wurst-Imperium/Wurst-Client-Bugs#108]
#### Other Information: Regen crashes me :(
- Wurst Client version: v3.4 
- Operating system: Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by qbus2002** [comment]
anti cheat blocks it or other packet controller blocks it
