### ISSUE TITLE
Report bug...bug

### ISSUE THREAD

**Issue by Marcusband** [Wurst-Imperium/Wurst-Client-Bugs#110]
It showed Up that I needed to report a bug so i went to do it, However, everytime i press report bug it says and error has occurred and i can't go back to game either. Its not allowing me to use the bug again

#### How to Reproduce the Bug
I am not sure its when you accidentally use a certain hack it may have been fastplace
#### Other Information
- Wurst Client version: 1.8
- Operating system: Windos OS 8.1

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Yeah, it's deprecated, also it is removed in Wurst 3.0 update.
