### ISSUE TITLE
yo

### ISSUE THREAD

**Issue by VeritasDL** [Wurst-Imperium/Wurst-Client-Bugs#117]
#### Description of the Bug
Replace this text with a description of the bug that you are reporting. What did you expect to happen? What happened instead?
The Brightness option in video settings keeps being set to 50%, shits annoying
#### How to Reproduce the Bug
Replace this text with a list of the necessary steps to reproduce the bug. What does one need to do in order for this bug to occur?
set brightness to 100%, re open settings its at 50%
#### Other Information
- Wurst Client version: 4.0
- Operating system: win 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Stego27** [comment]
This is better:
**Description of the Bug:**
The Brightness option in video settings keeps being set to 50%, shits annoying

**How to Reproduce the Bug:**
set brightness to 100%, reopen settings its at 50%

**Other Information:**
Wurst Client version: 4.0
Operating system: win 7


I have read and understood the Bug Tracker Rules before posting this bug report and filled out the template above with the correct information.
