### ISSUE TITLE
NoHurtCam doesn't work

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client-Bugs#12]
#### Description of the Bug
NoHurtCam has to block shaking when we're attacked. But Minecraft shakes as normally.

#### How to Reproduce the Bug
Open NoHurtCam and tell someone to attack you.

#### Other Information
- Wurst Client version: older than MC 1.7 all versions.
- Operating system: Mac OS 10.11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThisTestUser** [comment]
NoHurtcam was never implanted into the minecraft code.

**Comment by mcccs** [comment]
Yep.
