### ISSUE TITLE
LogSpammer Bug

### ISSUE THREAD

**Issue by xSirAndrew** [Wurst-Imperium/Wurst-Client-Bugs#120]
#### Description of the Bug
R I expected it to spam the logs cause logspammer but instead I got kicked.

#### How to Reproduce the Bug
 1. Launch Wurst 4.0 2. Join server (Only tried on a 1.10 Spigot) 3. Enable logspammer 4. Will be kicked for Invalid book data. Dont use logspammer or you'll be kicked.

#### Other Information
- Wurst Client version: Wurst 4.0 (Minecraft 1.10)
- Operating system: Windows 7(64 bit)

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by xSirAndrew** [comment]
Update: I've tried on a spigot 1.9.4 and had creative mode and it worked. I was using Wurst 4.0 (Mc 1.10) still on the server. Potentially requires creative? I also tried reconnecting with it still on after a "Invalid book data!" kick and it says "Invalid Trade Data"

**Comment by TheRipuliini** [comment]
I have the Same problem. I haven't figured how do I get the LogSpammer off...

**Comment by xSirAndrew** [comment]
Just go into singleplayer and turn it off, I sometimes have to do that for nuker.

**Comment by TheRipuliini** [comment]
thx for the help :)
