### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Innocent-Traitor** [Wurst-Imperium/Wurst-Client-Bugs#124]
#### Description of the Bug
I was playing survival games to see what you guys added in the new version but then my game crashes for no reason sometimes.
#### How to Reproduce the Bug
Play the game and it crashed repeatly.

#### Other Information
- Wurst Version: 4.0
- Operating system: Windows 10
---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Innocent-Traitor** [comment]
This is the crash report

`---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Oops.

Time: 7/18/16 10:13 AM
Description: Firing Wurst event

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at tk.wurst_client.mods.ChestEspMod.onRender(ChestEspMod.java:49)
	at tk.wurst_client.events.RenderEvent.fire(RenderEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1496)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1337)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1142)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1133)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at tk.wurst_client.mods.ChestEspMod.onRender(ChestEspMod.java:49)
	at tk.wurst_client.events.RenderEvent.fire(RenderEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.RenderEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1496)
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1337)

-- Affected level --
Details:
	Level name: MpServer
	All players: 16 total; [EntityPlayerSP['Innocent_T'/33385, l='MpServer', x=6948.01, y=17.23, z=-104.70], EntityOtherPlayerMP['stefanrockz'/0, l='MpServer', x=6911.14, y=63.45, z=-153.34], EntityOtherPlayerMP['sanderhuussen6'/1, l='MpServer', x=6884.50, y=63.00, z=-159.50], EntityOtherPlayerMP['LouDragon'/2, l='MpServer', x=6868.59, y=16.84, z=-176.67], EntityOtherPlayerMP['jorge_04'/4, l='MpServer', x=6887.45, y=17.24, z=-182.95], EntityOtherPlayerMP['IlaydaPeys'/5, l='MpServer', x=6886.93, y=62.00, z=-132.08], EntityOtherPlayerMP['Frosty_SlimeMLG'/6, l='MpServer', x=6854.64, y=61.00, z=-130.69], EntityOtherPlayerMP['XxFireBoyGamerxX'/7, l='MpServer', x=6912.19, y=62.89, z=-133.63], EntityOtherPlayerMP['Joeytje040'/8, l='MpServer', x=6865.72, y=62.86, z=-123.22], EntityOtherPlayerMP['0bsidianCreeper'/9, l='MpServer', x=6894.58, y=62.00, z=-166.11], EntityOtherPlayerMP['JJDgames'/10, l='MpServer', x=6891.47, y=62.88, z=-133.25], EntityOtherPlayerMP['whiteneko'/11, l='MpServer', x=6889.52, y=62.00, z=-121.82], EntityOtherPlayerMP['CharlieBoy0072'/12, l='MpServer', x=6887.70, y=62.88, z=-134.90], EntityOtherPlayerMP['Crxftinq_SlimeX'/13, l='MpServer', x=6891.64, y=70.00, z=-135.79], EntityOtherPlayerMP['Crxftinq_Dino'/14, l='MpServer', x=6910.03, y=63.02, z=-149.37], EntityOtherPlayerMP['FlashGamer'/15, l='MpServer', x=6845.55, y=17.42, z=-136.27]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-999999,575,-999999), Chunk: (at 1,35,1 in -62500,-62500; contains blocks -1000000,0,-1000000 to -999985,255,-999985), Region: (-1954,-1954; contains chunks -62528,-62528 to -62497,-62497, blocks -1000448,0,-1000448 to -999937,255,-999937)
	Level time: 1027550555 game time, 5210916000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 36 total; [EntityOtherPlayerMP['XxFireBoyGamerxX'/7, l='MpServer', x=6903.50, y=63.00, z=-155.50], EntityOtherPlayerMP['Joeytje040'/8, l='MpServer', x=6864.59, y=63.00, z=-129.58], EntityOtherPlayerMP['0bsidianCreeper'/9, l='MpServer', x=6894.50, y=63.00, z=-159.50], EntityOtherPlayerMP['JJDgames'/10, l='MpServer', x=6894.50, y=63.00, z=-109.55], EntityOtherPlayerMP['whiteneko'/11, l='MpServer', x=6868.54, y=63.00, z=-120.44], EntityOtherPlayerMP['CharlieBoy0072'/12, l='MpServer', x=6884.31, y=63.00, z=-109.60], EntityOtherPlayerMP['IlaydaPeys'/5, l='MpServer', x=6886.93, y=62.00, z=-132.08], EntityOtherPlayerMP['Crxftinq_SlimeX'/13, l='MpServer', x=6910.50, y=63.00, z=-148.50], EntityOtherPlayerMP['Crxftinq_Dino'/14, l='MpServer', x=6868.68, y=63.00, z=-148.39], EntityOtherPlayerMP['FlashGamer'/15, l='MpServer', x=6875.50, y=63.00, z=-155.50], EntityOtherPlayerMP['stefanrockz'/0, l='MpServer', x=6911.14, y=63.45, z=-153.34], EntityOtherPlayerMP['sanderhuussen6'/1, l='MpServer', x=6884.50, y=63.00, z=-159.50], EntityOtherPlayerMP['LouDragon'/2, l='MpServer', x=6868.59, y=16.84, z=-176.67], EntityOtherPlayerMP['jorge_04'/4, l='MpServer', x=6887.45, y=17.24, z=-182.95], EntityOtherPlayerMP['IlaydaPeys'/5, l='MpServer', x=6886.93, y=62.00, z=-132.08], EntityOtherPlayerMP['Crxftinq_SlimeX'/13, l='MpServer', x=6891.64, y=70.00, z=-135.79], EntityOtherPlayerMP['Frosty_SlimeMLG'/6, l='MpServer', x=6854.64, y=61.00, z=-130.69], EntityOtherPlayerMP['XxFireBoyGamerxX'/7, l='MpServer', x=6912.19, y=62.89, z=-133.63], EntityOtherPlayerMP['Joeytje040'/8, l='MpServer', x=6865.72, y=62.86, z=-123.22], EntitySheep['Sheep'/16, l='MpServer', x=6866.50, y=19.00, z=-86.50], EntityOtherPlayerMP['0bsidianCreeper'/9, l='MpServer', x=6894.58, y=62.00, z=-166.11], EntitySheep['Sheep'/17, l='MpServer', x=6867.50, y=19.00, z=-82.50], EntityOtherPlayerMP['JJDgames'/10, l='MpServer', x=6891.47, y=62.88, z=-133.25], EntitySheep['Sheep'/18, l='MpServer', x=6865.50, y=19.00, z=-81.50], EntityOtherPlayerMP['whiteneko'/11, l='MpServer', x=6889.52, y=62.00, z=-121.82], EntityOtherPlayerMP['CharlieBoy0072'/12, l='MpServer', x=6887.70, y=62.88, z=-134.90], EntityOtherPlayerMP['Crxftinq_SlimeX'/13, l='MpServer', x=6891.64, y=70.00, z=-135.79], EntityOtherPlayerMP['Crxftinq_Dino'/14, l='MpServer', x=6910.03, y=63.02, z=-149.37], EntityOtherPlayerMP['FlashGamer'/15, l='MpServer', x=6845.55, y=17.42, z=-136.27], EntityPlayerSP['Innocent_T'/33385, l='MpServer', x=6948.01, y=17.23, z=-104.70], EntityOtherPlayerMP['stefanrockz'/0, l='MpServer', x=6910.50, y=63.00, z=-120.50], EntityOtherPlayerMP['sanderhuussen6'/1, l='MpServer', x=6884.50, y=63.00, z=-159.50], EntityOtherPlayerMP['LouDragon'/2, l='MpServer', x=6864.50, y=63.00, z=-139.50], EntityOtherPlayerMP['jorge_04'/4, l='MpServer', x=6913.78, y=63.00, z=-129.62], EntityOtherPlayerMP['IlaydaPeys'/5, l='MpServer', x=6914.50, y=63.00, z=-139.50], EntityOtherPlayerMP['Frosty_SlimeMLG'/6, l='MpServer', x=6875.50, y=63.00, z=-113.50]]
	Retry entities: 0 total; []
	Server brand: BungeeCord (git:BungeeCraft-Bootstrap:1.9.0-SNAPSHOT:c7e59ab:unknown) <- Spigot
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
	Minecraft Version: 1.10
	Wurst Client Version: 4.0 (latest: 4.0)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 140344304 bytes (133 MB) / 332709888 bytes (317 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.X Wurst Client
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Celeron(R) CPU N2830 @ 2.16GHz`

**Comment by pvppro19** [comment]
had this same problem. hope it gets fixed
