### ISSUE TITLE
MenuWalk doesn't work when we click ESC button.

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client-Bugs#13]
#### Description of the Bug
After I enabled MenuWalk and opened the ESC menu, I can't walk.

#### How to Reproduce the Bug
Enable MenuWalk and open the ESC menu. Then use WASD keys.

#### Other Information
- Wurst Client version: All MC 1.8 clients.
- Operating system: Mac OS 10.11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThisTestUser** [comment]
Using ESC pauses the game, and it really shouldn't walk there as it would bug out singleplayer.

**Comment by mcccs** [comment]
In multiplayer too.

**Comment by Alexander01998** [comment]
That's intended. Using MenuWalk in the Esc menu would cause a crash once you leave the server. We had that in the update where MenuWalk was added (I don't remember the version).
