### ISSUE TITLE
Gui

### ISSUE THREAD

**Issue by CosmicNoodle** [Wurst-Imperium/Wurst-Client-Bugs#150]
Every time that i press Left CTRL, It will not open the gui and i have no controls with Left CRTL as it, nothing happens when i press Left CRTL

Press Left CRTL and nothing happend

#### Other Information
- Wurst Client version:  4.0
- Operating system:  1.10?

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ivanjenajjnasvetu** [comment]
need to bind it i mean

**Comment by CosmicNoodle** [comment]
that wont work either the only things that will .t (hack)
