### ISSUE TITLE
Game randomly crashing

### ISSUE THREAD

**Issue by pvppro19** [Wurst-Imperium/Wurst-Client-Bugs#154]
#### Description of the Bug
 When I am playing, the game will randomly crash. For example, just use wurst 20 min. or so and the game will just suddenly turn white and stop responding. Then the game closes. It doesn't matter if you have mods,hacks etc. toggled.

#### How to Reproduce the Bug
 Just play for a while and the game will crash.
#### Other Information
- Wurst Client version:4.0 
- Operating system: Windows 10 home
[crash-2016-07-23_21.38.19-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/380507/crash-2016-07-23_21.38.19-client.txt)

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by techano** [comment]
Im having the same problem hopefully they fix it soon :8ball:+1:
