### ISSUE TITLE
My Game keeps crashes

### ISSUE THREAD

**Issue by BigFlathead** [Wurst-Imperium/Wurst-Client-Bugs#158]
#### Description of the Bug
I got Wurst yesterday and it was working fine. I wake up this morning and It keeps crashing when I try to join a server.

#### How to Reproduce the Bug
I dont know what I did but it keep crashing on me this morning
#### Other Information
- Wurst Client version: 4.0
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by UltimateBoomer** [comment]
Try deleting your wurst folder
