### ISSUE TITLE
Fly Hacks causes crash

### ISSUE THREAD

**Issue by VincentCandela** [Wurst-Imperium/Wurst-Client-Bugs#166]
#### Other Information
- Wurst Client version: v4.0
- Operating system: windows 10

### Crash Report
[crash-2016-07-30_17.46.09-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/392103/crash-2016-07-30_17.46.09-client.txt)

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by IrrealPower** [comment]
From the crash report, it seems that it's a Rendering crash, caused from ChestESP while updating the world map and rendering the box around the chest. Peace out!
