### ISSUE TITLE
Crashes whenever I get into a game and when I use regen it also crashes even with YesCheat+

### ISSUE THREAD

**Issue by PlumpBear24** [Wurst-Imperium/Wurst-Client-Bugs#167]
#### Description of the Bug
When I was trying to get into a game on Mineplex (I don't know if its just on Mineplex) right as it started it suddenly crashed. However it didn't crash when I was spectating but right as the next game started it crashed. It also crashes when I use regen with YesCheat+.

#### How to Reproduce the Bug
Go to blockhunt on Mineplex (I've only tried this on blockhunt) click spectate and notice that it doesn't kick you but when your in the pre game lobby and the game starts it kicks you. And for the regen crash turn on regen and go into a game when you get hit it crashes you even with YesCheat+.

#### Other Information
- Wurst Client version: V 4.0
- Operating system: EliteBook laptop w/ windows 10 and Apple IMac w/ windows 10

--- I have tried this on a laptop and desktop both of them show the same result on blockhunt I will further investigate this to other game modes and post my results in the comments

**Comment by PlumpBear24** [comment]
I tried most other game modes and most of them had the same result with the crash right as the game started, however team death match on Mineplex didn't crash I was able to play almost a full match then i lost connection :D but maybe that's just me. I hope these bugs get fixed in the future. Keep up the good work Alexander.

**Comment by TheFRESHvinc3** [comment]
How did you fix it?

**Comment by PlumpBear24** [comment]
I haven't yet I'm trying to find a solution.
