### ISSUE TITLE
AutoTool & AutoMine Compatibility

### ISSUE THREAD

**Issue by Hgwells1** [Wurst-Imperium/Wurst-Client-Bugs#168]
#### Description of the Bug

Autotool does not work while automine is active, what I mean by this is that if the pick breaks it will not switch to the next available pick but will just keep mining albeit with an empty hand now.
#### How to Reproduce the Bug

Activate autotool and automine, doesn't matter what picks you are using but when it breaks it will not switch to the next available pickaxe (inv or hotbar).
I first noticed this problem while using a cobble generator on a skyblock server and mining directly ahead.
#### Other Information
- Wurst Client version: currently using Wurst 4 however this issue was present in 3 as well
- Operating system: Windows 7 & Windows 10, issue is the same regardless

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by AAgamesnl** [comment]
true
