### ISSUE TITLE
SmashNuker

### ISSUE THREAD

**Issue by TheWoolRedstone** [Wurst-Imperium/Wurst-Client-Bugs#170]
#### Description of the Bug
I accendently turned on SmashNuker and then it crashed

#### How to Reproduce the Bug
Just select SmashNuker
#### Other Information
- Wurst Client version: 4.0
- Operating system: Win10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Why did you do that?

Time: 02/08/16 9:23 PM
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
	at net.minecraft.world.World.func_189509_E(World.java:257)
	at net.minecraft.world.World.getBlockState(World.java:872)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)
	at net.minecraft.world.World.updateEntities(World.java:1790)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
	at net.minecraft.client.Minecraft.run(Minecraft.java:403)
	at net.minecraft.client.main.Main.main(Main.java:120)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.world.World.func_189509_E(World.java:257)
	at net.minecraft.world.World.getBlockState(World.java:872)
	at tk.wurst_client.mods.NukerMod.find(NukerMod.java:277)
	at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:119)
	at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
	Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
	at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
	at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:230)
	at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1970)
	at net.minecraft.world.World.updateEntity(World.java:1940)

-- Entity being ticked --
Details:
	Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
	Entity ID: 3912
	Entity Name: TkePjstnRedstone
	Entity's Exact location: -119.50, 181.10, -226.50
	Entity's Block location: World: (-120,181,-227), Chunk: (at 8,11,13 in -8,-15; contains blocks -128,0,-240 to -113,255,-225), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.updateEntities(World.java:1790)

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['TkePjstnRedstone'/3912, l='MpServer', x=-119.50, y=181.10, z=-226.50], EntityOtherPlayerMP['superman011'/773, l='MpServer', x=-116.63, y=45.00, z=-131.20]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (8,4,8), Chunk: (at 8,0,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 465691 game time, 465691 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 32 total; [EntityPlayerSP['TkePjstnRedstone'/3912, l='MpServer', x=-157.57, y=-71.56, z=-401.84], EntityOtherPlayerMP['superman011'/773, l='MpServer', x=-116.63, y=45.00, z=-131.20], EntityOtherPlayerMP['superman011'/773, l='MpServer', x=-116.63, y=45.00, z=-131.20], EntityPlayerSP['TkePjstnRedstone'/3912, l='MpServer', x=-119.50, y=181.10, z=-226.50], EntityOtherPlayerMP['superman011'/773, l='MpServer', x=-116.63, y=45.00, z=-131.20], EntityFallingBlock['Falling Block'/5979, l='MpServer', x=-135.50, y=-93.00, z=-295.50], EntityFallingBlock['Falling Block'/5981, l='MpServer', x=-133.50, y=-87.26, z=-290.50], EntityFallingBlock['Falling Block'/5984, l='MpServer', x=-135.50, y=-79.63, z=-292.50], EntityFallingBlock['Falling Block'/5986, l='MpServer', x=-133.50, y=-77.35, z=-290.50], EntityFallingBlock['Falling Block'/5989, l='MpServer', x=-135.50, y=-73.08, z=-289.50], EntityFallingBlock['Falling Block'/5992, l='MpServer', x=-135.50, y=-63.57, z=-289.50], EntityFallingBlock['Falling Block'/5995, l='MpServer', x=-135.50, y=-57.38, z=-289.50], EntityFallingBlock['Falling Block'/5998, l='MpServer', x=-135.50, y=-51.34, z=-289.50], EntityFallingBlock['Falling Block'/6000, l='MpServer', x=-134.50, y=-48.39, z=-290.50], EntityFallingBlock['Falling Block'/6002, l='MpServer', x=-135.50, y=-42.61, z=-293.50], EntityFallingBlock['Falling Block'/6004, l='MpServer', x=-133.50, y=-41.58, z=-294.50], EntityFallingBlock['Falling Block'/6006, l='MpServer', x=-137.50, y=-31.62, z=-292.50], EntityFallingBlock['Falling Block'/6008, l='MpServer', x=-135.50, y=-26.45, z=-295.50], EntityFallingBlock['Falling Block'/6010, l='MpServer', x=-133.50, y=-22.51, z=-290.50], EntityFallingBlock['Falling Block'/6012, l='MpServer', x=-135.50, y=-16.84, z=-292.50], EntityFallingBlock['Falling Block'/6014, l='MpServer', x=-133.50, y=-17.81, z=-290.50], EntityFallingBlock['Falling Block'/6016, l='MpServer', x=-135.50, y=-10.35, z=-289.50], EntityFallingBlock['Falling Block'/6018, l='MpServer', x=-135.50, y=-6.42, z=-289.50], EntityFallingBlock['Falling Block'/6021, l='MpServer', x=-135.50, y=-2.83, z=-289.50], EntityFallingBlock['Falling Block'/6024, l='MpServer', x=-135.50, y=0.39, z=-289.50], EntityFallingBlock['Falling Block'/6027, l='MpServer', x=-134.50, y=1.85, z=-290.50], EntityFallingBlock['Falling Block'/6030, l='MpServer', x=-135.50, y=1.88, z=-293.50], EntityFallingBlock['Falling Block'/6033, l='MpServer', x=-133.50, y=7.61, z=-294.50], EntityFallingBlock['Falling Block'/6035, l='MpServer', x=-137.50, y=8.26, z=-292.50], EntityFallingBlock['Falling Block'/6037, l='MpServer', x=-135.50, y=9.39, z=-295.50], EntityFallingBlock['Falling Block'/6039, l='MpServer', x=-133.50, y=8.93, z=-290.50], EntityFallingBlock['Falling Block'/6042, l='MpServer', x=-135.50, y=10.01, z=-292.50]]
	Retry entities: 0 total; []
	Server brand: vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
	at net.minecraft.client.Minecraft.run(Minecraft.java:424)
	at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
	Minecraft Version: 1.10
	Wurst Client Version: 4.0 (latest: 4.0)
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 133573720 bytes (127 MB) / 290586624 bytes (277 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: 1.10.X Wurst Client
	LWJGL: 2.9.4
	OpenGL: AMD Radeon HD 7640G GL version 4.5.13399 Compatibility Profile Context 15.201.1151.1008, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-4500M APU with Radeon(tm) HD Graphics 
#@!@# Game crashed! Crash report saved to: C:\Users\Hans\AppData\Roaming\.minecraft\crash-reports\crash-2016-08-02_21.23.13-client.txt
#@!@# Please report this crash at: https://www.wurst-client.tk/bugs/

**Comment by qwestfrost** [comment]
Are you using Wurst 1.10 or below?
