### ISSUE TITLE
Game crashes after a couple of minutes without any reason

### ISSUE THREAD

**Issue by MineStone** [Wurst-Imperium/Wurst-Client-Bugs#171]
#### Description of the Bug
I was playing on Mineplex with wurst client for 1.10.X and the game crashed
These is the 4th time this bug appears

#### How to Reproduce the Bug
Play minecraft on a server with wurst and set YesCheat+ to Mineplex anticheat,
enable BoatFly, TrueSight, AntiBlind, Tracers, Trajectories, Anti-knockback

#### Other Information
- Wurst Client version: Wurst for MC 1.10.X
- Operating system: Windows 10
- Graphic card: NVIDIA GEFORCE GTX 960m
- Launcher logs: http://pastebin.com/dWHLVKTt
- Crash report: http://pastebin.com/iQuNvBKw

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by techano** [comment]
i have the same thing without anything on :+1:
