### ISSUE TITLE
Step-up bug.

### ISSUE THREAD

**Issue by Blinky1337** [Wurst-Imperium/Wurst-Client-Bugs#173]
#### Description of the Bug
Step-up is included in the hack, it's always on and can't be turned off.
What happened instead?

#### How to Reproduce the Bug
When you walk to a block it's auto-jumping on the block. As the step-up mode is on, but it's not.

#### Other Information
- Wurst Client version: v4.0
- Operating system:  Windows 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Opzon** [comment]
have this issue too. Very annoying :+1:
