### ISSUE TITLE
AutoSteal does not work correctly anymore 

### ISSUE THREAD

**Issue by heyitsjuggz** [Wurst-Imperium/Wurst-Client-Bugs#174]
It only takes one item at a time
from the chest please help this helps in hunger games
#### How to Reproduce the Bug
Replace this text with a list of the necessary steps to reproduce the bug. What does one need to do in order for this bug to occur?

#### Other Information
- Wurst Client version: 
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by qwestfrost** [comment]
I think AutoSteal always only took one item at a time. Even if it didn't, it's not an issue, it's probably a way to fix glitches when trying to take multiple items at once, which the items go back to the chest.

**Comment by heyitsjuggz** [comment]
Thank you
