### ISSUE TITLE
SmashNuker is obviously broken.

### ISSUE THREAD

**Issue by Duodong** [Wurst-Imperium/Wurst-Client-Bugs#181]
#### Description of the Bug
I was playing on some server and accidentally brushed the shortcut key for smashnuker. The game immediately crashed. Now whenever I open an SP or multiplayer world, my game instantly crashes.

#### How to Reproduce the Bug

Enable SmashNuker

#### Other Information
- Wurst Client version: 4
- Operating system: OSX 10.10.4

--- I notice you've been systematically closing threads pertaining to this issue in particular. This bug (or whatever it is) is well noticed and well documented. Please offer a fix or any kind of helpful response. Preferably some way to edit the enabled mods without opening the GUI in-game.

P.S. I've also read into your (Alexander01998) responses. 
Just because this issue doesn't happen to YOU doesn't mean it doesn't happen to many other people.

Thank you

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by derpydumbsquids** [comment]
Follow these steps from 1 to 3, (they are pictures)  !Nuker crash fix!  (Fix By: KR tech
Others may found this fix so credits to every one that found this fix.)

![step1](https://cloud.githubusercontent.com/assets/20975257/17599374/5ebc63a2-5fc4-11e6-9919-ba305c11ab95.PNG)
![step2](https://cloud.githubusercontent.com/assets/20975257/17599375/6159e922-5fc4-11e6-9aff-c5c2e7b834e1.PNG)
![step3](https://cloud.githubusercontent.com/assets/20975257/17599379/6421d714-5fc4-11e6-814f-b483ba11c677.PNG)
