### ISSUE TITLE
smash nuker

### ISSUE THREAD

**Issue by epicjoshf** [Wurst-Imperium/Wurst-Client-Bugs#183]
#### Description of the Bug

 i accidentally clicked on smash nuker then it crashed the game. And i tried downloaded the wurst client again smash nuker was still there. how do i fix it 

#### How to Reproduce the Bug
turn on smash nuker

#### Other Information
- Wurst Client version: 
- Operating system:windows ten 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by derpydumbsquids** [comment]
Follow these steps from 1 to 3, (they are pictures)  !Nuker crash fix!  (Fix By: KR tech
Others may found this fix so credits to every one that found this fix.)


![step1](https://cloud.githubusercontent.com/assets/20975257/17599259/df232306-5fc3-11e6-91e2-8021fa8f1706.PNG)
![step2](https://cloud.githubusercontent.com/assets/20975257/17599269/e93036ae-5fc3-11e6-950d-dcb4e190240f.PNG)
![step3](https://cloud.githubusercontent.com/assets/20975257/17599270/ebe652de-5fc3-11e6-96a4-8c2e056babc1.PNG)
