### ISSUE TITLE
THIS IS A FIX FOR THE "NUKER CRASH"

### ISSUE THREAD

**Issue by derpydumbsquids** [Wurst-Imperium/Wurst-Client-Bugs#186]
Follow these steps from 1 to 3, (they are pictures)  !Nuker crash fix!  (Fix By: KR tech
Others may found this fix so credits to every one that found this fix.)

![step1](https://cloud.githubusercontent.com/assets/20975257/17599435/ac6e123a-5fc4-11e6-9afa-ea1da329521e.PNG)
![step2](https://cloud.githubusercontent.com/assets/20975257/17599440/ae873236-5fc4-11e6-8d99-286530ff10b3.PNG)
![step3](https://cloud.githubusercontent.com/assets/20975257/17599443/b13957ac-5fc4-11e6-829f-b74d2ab88132.PNG)

**Comment by PigglesPorkchops** [comment]
What version of Wurst is this? I mine doesnt show a modlues thingymagig

**Comment by derpydumbsquids** [comment]
I think this one is Wurst for 1.8, but it may be that I installed it differently. I will try to see what I can do.

**Comment by derpydumbsquids** [comment]
Show me a screen-shot of your ".minecraft" folder and "versions" in the ".minecraft" folder.

**Comment by qwestfrost** [comment]
I thought the guidelines stated that this issue tracker was for bug threads and ONLY bug threads? Also, the fix is outdated.
