### ISSUE TITLE
regen disconections

### ISSUE THREAD

**Issue by CeesSquareMan** [Wurst-Imperium/Wurst-Client-Bugs#194]
#### Description of the Bug
in Mineplex, when i lost health i wanted to turn on regen. so i turned it on and minecraft crashed. this happens all the time when i activate regen

#### How to Reproduce the Bug
1. lose health.
2. activate regen

#### Other Information
- Wurst Client version: 4.0
- Operating system: um... pc?

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by RoccoDeveloping** [comment]
I suppose you're using Windows ("um... pc?") Which version? You can find out by right-clicking on My Computer. Select Properties.

**Comment by CeesSquareMan** [comment]
Ye I use windows

**Comment by RoccoDeveloping** [comment]
Which version? Windows 7? 8? 10? XP? Vista?

**Comment by CeesSquareMan** [comment]
Windows 7

**Comment by RoccoDeveloping** [comment]
You should post your Crash Report
