### ISSUE TITLE
Wierd Wurst

### ISSUE THREAD

**Issue by rockersr** [Wurst-Imperium/Wurst-Client-Bugs#195]
#### Description of the Bug
I have wurst 1.8 and 1.10 versions on my pc, I use wurst 1.8 on a cracked server then switched to 1.10 to play on an anarchy server, and it acted like it was the 1.8 version
#### How to Reproduce the Bug
go on 1.8, log out, go on 1.10

#### Other Information
- Wurst Client version: 1.8 and 1.10
- Operating system: Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by qwestfrost** [comment]
Are you sure you chose the right version? Can you send any screenshots?

**Comment by rockersr** [comment]
I can't provide and screen shots, but I tripled checked I was on that version

**Comment by rockersr** [comment]
I'm pretty sure I have the right version activated
