### ISSUE TITLE
Killaura Not Bypassing WatchDog

### ISSUE THREAD

**Issue by IBinary1337** [Wurst-Imperium/Wurst-Client-Bugs#198]
#### Description of the Bug
I was using Killaura on Hypixel. I had the bypass level set to "Ghost Mode". I expected it to bypass WatchDog but instead I got banned by WatchDog.
I had invisibles turned off.
#### How to Reproduce the Bug
1. Go on Hypixel anti play Skywars.
2. You will get banned after playing a while.

I don't know if this caused it, but just before I got banned there was this player who floated in front of my face shortly before I got banned. He was visible and had a diamond chestplate and golden leggings.

#### Other Information
- Wurst Client version: Wurst 4.0
- Operating system: Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by pvppro19** [comment]
killaura on wurst does not bypass completely because the visible bot you saw was an aura bot. if you hit it multiple times,you get banned. wurst can not bypass that because it is visible. That's what makes watchdog so good

**Comment by IBinary1337** [comment]
i tried it with an mcleaks account (took me forever to find one), with 150 FOV, and i still get banned.
