### ISSUE TITLE
Fasteat doesn't work

### ISSUE THREAD

**Issue by DaveyL2013** [Wurst-Imperium/Wurst-Client-Bugs#206]
#### Description of the Bug:

When I used fasteat, I expected eating and drinking to happen faster-unhappen-rehappen, that's pretty much the same as fastbreak, that's normal. When I turned the hack on however I was surprised to find that it did **absolutely nothing!**
#### How to Reproduce the Bug

Simply try to use fasteat... and find that it does **nothing!**
#### Other Information
- Wurst Client version: 4.0
- Operating system: [Mac OS X 10.11.5](http://www.apple.com/osx/)

**Comment by supertassu** [comment]
Please tell your YesCheatPlus level.
