### ISSUE TITLE
Gui Scalling Issue

### ISSUE THREAD

**Issue by BanForFun** [Wurst-Imperium/Wurst-Client-Bugs#209]
There is a gui scalling issue in wurst 1.8 with bigger screens. (I Think 22 inches and above)

In minecraft if you have set the: "Options > Video Settings > GUI Scale" to Auto and you have a bigger that 22 inches screen, the gui gets even bigger than if you have the gui scale set to large. When i use wurst that doesn't happend and the click gui doesn't work properly. Ex. (See where my cursor is and what is highlited)

![default](https://cloud.githubusercontent.com/assets/21692812/18180889/8a3860de-7091-11e6-99f7-1528c1577e7d.PNG)

When i click, it toggles the hack i have my cursor on, but i can't adjust the sliders (Or Trackbars ...... I hope you understood)

The new wurst gui works fine.

Wurst Version: 2.21.2
Operating System: Windows 8.1 Pro

**Comment by Alexander01998** [comment]
> The new wurst gui works fine.

That's one of the reasons why the old GUI was removed in later versions.
