### ISSUE TITLE
SpeedNuker is broken.

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst-Client-Bugs#21]
#### Description of the Bug
SpeedNuker doesn't work anymore due to MC 1.9's built-in anticheat.

#### How to Reproduce the Bug
Enable SpeedNuker.

#### Other Information
- Wurst Client version: 3.0
- Operating system: Mac OS X 11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by vovanre** [comment]
> SpeedNuker doesn't work anymore due to MC 1.9's built-in anticheat.

Nope, this client side bug. I found what was wrong, pull requests soon
