### ISSUE TITLE
smash nuker SUCKS!

### ISSUE THREAD

**Issue by 69Mojang69** [Wurst-Imperium/Wurst-Client-Bugs#212]
every time i use Wurst Hacked Client 1.10X i crash and it wont let me on ANYMORE now so can you please make a update to Wurst?!!!!

**Comment by liach** [comment]
Crash report plz

**Comment by 69Mojang69** [comment]
um everything turns black and when i move my mouse the curser doesnt show
up until i move it like a foot up
