### ISSUE TITLE
ppl keep saying im spinning 360. 

### ISSUE THREAD

**Issue by Pallemaster1400** [Wurst-Imperium/Wurst-Client-Bugs#219]
#### Description of the Bug
Well as titel says every one keep saying that im spinning my head 360 constant, and i dont know whats going on

#### How to Reproduce the Bug
All i have on is 
AutoSprint
Fullbright
NameTags
PlayerESP
Tracers

#### Other Information
- Wurst Client version: v2.21.2
- Operating system: Win7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Alexander01998** [comment]
You have Derp enabled.

**Comment by Pallemaster1400** [comment]
no all mods was off and it still happend
