### ISSUE TITLE
Non-AlphaNumeric Keystrokes broke Navigator Search

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst-Client-Bugs#22]
#### Description of the Bug
[View GIF](https://cloud.githubusercontent.com/assets/11584045/15044431/4d403196-12dd-11e6-8a79-49c3b1e723d3.gif)
As you see in the GIF, I pressed arrow keys where the search results are gone.

#### How to Reproduce the Bug
While you're searching, press arrow keys. When you press ⌫, search results will appear.

#### Other Information
- Wurst Client version: 3.0
- Operating system: Mac OS X 11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

// TODO: Improve title

**Comment by ThisTestUser** [comment]
There is also a bug where the buttons start flashing for no reason after using the back arrow key with text on the screen.
