### ISSUE TITLE
Blindkeys reset

### ISSUE THREAD

**Issue by LordWitherStorm** [Wurst-Imperium/Wurst-Client-Bugs#229]
The blindKeys keep resetting each time you restart the game and load the client 1.10.x
I don't know if that was supposed to happen but its pissing me off

**Comment by GoldenOakland** [comment]
Your not the only one. I cannot remove the key bind for the navigator command. After the client auto updates it been causing me so much annoyance. Remove the key bind and reopen client. Keybind adds itself. Change the key bind and reopen client. Keybind adds itself and now you have 2 navigator keybind. The default command it uses for the command is the same key i use for crouching.
