### ISSUE TITLE
Trouble joining 1.9.2 server

### ISSUE THREAD

**Issue by MrGeary** [Wurst-Imperium/Wurst-Client-Bugs#23]
**Description of the Bug**
Okay so I've been playing on a private server with friends for some time and got bored so I tried to use the Wurst client and join the server but it shows 1.9.2 as being a server with a higher version than what the Wurst client is on. It was a vanilla server, and I can join other 1.9.2 servers, however those other ones are using server plugins such as bukkit.

**How to Reproduce the Bug**
Try to log on to a vanilla 1.9.2 server and see if it happens to you. (I hope it's not just me.)

**Other information**
- Wurst Client version: 3.0 
- Operating system: Windows 8.1

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThisTestUser** [comment]
1.9 clients are not compatible with 1.9.2 servers. There is no MCP for 1.9.2 so the client cannot be updated.

**Comment by Alexander01998** [comment]
> 1.9 clients are not compatible with 1.9.2 servers. There is no MCP for 1.9.2 so the client cannot be updated.

^
