### ISSUE TITLE
TrueSight doesnt show invisible entites. (MC 1.10)

### ISSUE THREAD

**Issue by GravelCZLP** [Wurst-Imperium/Wurst-Client-Bugs#230]
#### Description of the Bug

I expected that i will see the entity (Player) like in wurst 1.8, but i did not see anything 
#### How to Reproduce the Bug

Enable TrueSight and then spawn some invisible entity(Player), you will not be able to see it (unless you are using PlayerESP)
#### Other Information
- Wurst Client version: 4.1 
- Operating system: Linux Ubuntu 16.04 LTS

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by GravelCZLP** [comment]
i see how it is, https://github.com/Wurst-Imperium/Wurst-MC-1.10/blob/master/src/tk/wurst_client/mods/TrueSightMod.java that might be the cause, empty class :-1:

**Comment by AAgamesnl** [comment]
i love this mod      :(
