### ISSUE TITLE
Wurst keeps binding LCONTROL to Navigator.

### ISSUE THREAD

**Issue by omarsgifford14** [Wurst-Imperium/Wurst-Client-Bugs#233]
#### Description of the Bug

The bug makes it so that each time Wurst boots up, LCONTROL is bound to the navigator making it so that I have to remove they keybind every time just to use my sprint key as I prefer to have the navigator keybind set to RSHIFT.
#### How to Reproduce the Bug

Just remove the LCONTROL keybind and reboot the Wurst Client, the LCONTROL keybind for navigator should come back automatically.
#### Other Information
- Wurst Client version: 4.1
- Operating system: Mac OSX El Capitan
---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by lwaite9** [comment]
I have the same exact problem, it persists on Wurst 4.2

Wurst 4.0 left my keybinds as i saved them.
