### ISSUE TITLE
GUI Command

### ISSUE THREAD

**Issue by ifoliver** [Wurst-Imperium/Wurst-Client-Bugs#24]
I accidently deleted the gui keybind when deleting all of my others. And now there is absolutely no command I can put into the keybind to open the gui again

It should be fixed by adding a command like .gui or something similar.

#### Other Information
- Wurst Client version: 3.0
- Operating system: windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThisTestUser** [comment]
You can use the Wurst keybinds (in wurst options) to set up your keybinds.

**Comment by Alexander01998** [comment]
Wurst Options > Keybinds > Reset Keybinds
