### ISSUE TITLE
keybinds issue, wurst menu

### ISSUE THREAD

**Issue by Vonmagni** [Wurst-Imperium/Wurst-Client-Bugs#241]
Whenever I relaunch Minecraft, my keybind for the wurst menu adds the standard keybind for the menu (L Ctrl) so whenever I press it, it opens the menu so I have to change it back via Esc+wurst+keybinds and remove the keybind... its really annoying.

**Comment by lwaite9** [comment]
I too have the same problem, on wurst 4.1 and 4.2
Wurst 4.0 left my keybinds alone after i changed them once.

**Comment by Vonmagni** [comment]
Im on Wurst 4.2

**Comment by Vonmagni** [comment]
still same on Wurst 4.3
