### ISSUE TITLE
Opened a survival world and crashed

### ISSUE THREAD

**Issue by harvey232323** [Wurst-Imperium/Wurst-Client-Bugs#248]
I went on 1.10.x and tried to open a survival world. It opened with smash nuker and yes cheat plus on. When i pressed any key it crashed. Error was;

---------------- Wurst Client Crash Report ----------------
---- Please report this crash at: wurst-client.tk/bugs ----
// Don't be sad. I'll do better next time, I promise!

Time: 22/10/16 16:41
Description: Firing Wurst event

java.lang.NullPointerException: Firing Wurst event
    at net.minecraft.world.World.func_189509_E(World.java:254)
    at net.minecraft.world.World.getBlockState(World.java:869)
    at tk.wurst_client.mods.NukerMod.find(NukerMod.java:281)
    at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:121)
    at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)
    at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:222)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1987)
    at net.minecraft.world.World.updateEntity(World.java:1957)
    at net.minecraft.world.World.updateEntities(World.java:1807)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1887)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1113)
    at net.minecraft.client.Minecraft.run(Minecraft.java:403)
    at net.minecraft.client.main.Main.main(Main.java:120)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.world.World.func_189509_E(World.java:254)
    at net.minecraft.world.World.getBlockState(World.java:869)
    at tk.wurst_client.mods.NukerMod.find(NukerMod.java:281)
    at tk.wurst_client.mods.NukerMod.onUpdate(NukerMod.java:121)
    at tk.wurst_client.events.UpdateEvent.fire(UpdateEvent.java:22)

-- Affected event --
Details:
    Event class: tk.wurst_client.events.UpdateEvent
Stacktrace:
    at tk.wurst_client.events.EventManager.fire(EventManager.java:47)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:222)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1987)
    at net.minecraft.world.World.updateEntity(World.java:1957)

-- Entity being ticked --
Details:
    Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
    Entity ID: 1971
    Entity Name: MY USERNAME
    Entity's Exact location: -252.50, 67.00, 216.50
    Entity's Block location: World: (-253,67,216), Chunk: (at 3,4,8 in -16,13; contains blocks -256,0,208 to -241,255,223), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Entity's Momentum: 0.00, 0.00, 0.00
    Entity's Passengers: []
    Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.world.World.updateEntities(World.java:1807)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['MYUSERNAME'/1971, l='MpServer', x=-252.50, y=67.00, z=216.50]]
    Chunk stats: MultiplayerChunkCache: 246, 246
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-244,64,224), Chunk: (at 12,4,0 in -16,14; contains blocks -256,0,224 to -241,255,239), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 77 game time, 77 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 59 total; [EntityFallingBlock['Falling Block'/257, l='MpServer', x=-370.50, y=15.34, z=181.50], EntitySheep['Sheep'/917, l='MpServer', x=-209.50, y=69.00, z=255.50], EntitySheep['Sheep'/918, l='MpServer', x=-209.50, y=69.00, z=255.50], EntitySheep['Sheep'/919, l='MpServer', x=-209.50, y=69.00, z=254.50], EntitySheep['Sheep'/920, l='MpServer', x=-211.50, y=69.00, z=256.50], EntitySheep['Sheep'/538, l='MpServer', x=-324.50, y=64.00, z=274.55], EntitySheep['Sheep'/539, l='MpServer', x=-322.50, y=63.00, z=273.50], EntitySheep['Sheep'/540, l='MpServer', x=-324.50, y=64.00, z=275.50], EntityBat['Bat'/811, l='MpServer', x=-240.81, y=40.08, z=172.24], EntityChicken['Chicken'/812, l='MpServer', x=-246.01, y=65.00, z=200.33], EntityChicken['Chicken'/813, l='MpServer', x=-245.50, y=63.00, z=198.50], EntityChicken['Chicken'/814, l='MpServer', x=-246.50, y=63.00, z=198.50], EntityChicken['Chicken'/815, l='MpServer', x=-245.50, y=63.00, z=198.50], EntityChicken['Chicken'/816, l='MpServer', x=-246.50, y=64.00, z=223.50], EntityChicken['Chicken'/817, l='MpServer', x=-245.50, y=63.00, z=230.50], EntityChicken['Chicken'/818, l='MpServer', x=-250.50, y=65.00, z=228.50], EntityChicken['Chicken'/819, l='MpServer', x=-253.50, y=66.00, z=231.50], EntityPlayerSP['MY USERNAME'/1971, l='MpServer', x=-252.50, y=67.00, z=216.50], EntityChicken['Chicken'/820, l='MpServer', x=-248.50, y=64.00, z=230.50], EntitySquid['Squid'/692, l='MpServer', x=-287.56, y=60.60, z=210.07], EntityChicken['Chicken'/821, l='MpServer', x=-251.50, y=66.00, z=229.50], EntityChicken['Chicken'/693, l='MpServer', x=-274.50, y=68.00, z=271.50], EntityChicken['Chicken'/822, l='MpServer', x=-246.50, y=64.00, z=229.50], EntityChicken['Chicken'/694, l='MpServer', x=-276.50, y=68.00, z=269.50], EntityChicken['Chicken'/823, l='MpServer', x=-245.50, y=64.00, z=226.50], EntityChicken['Chicken'/695, l='MpServer', x=-275.50, y=68.00, z=269.50], EntityChicken['Chicken'/824, l='MpServer', x=-243.50, y=63.00, z=265.50], EntityChicken['Chicken'/696, l='MpServer', x=-278.50, y=68.00, z=272.50], EntityChicken['Chicken'/825, l='MpServer', x=-243.50, y=63.00, z=268.50], EntityChicken['Chicken'/826, l='MpServer', x=-244.50, y=63.00, z=267.50], EntityChicken['Chicken'/827, l='MpServer', x=-240.78, y=64.00, z=266.51], EntityChicken['Chicken'/575, l='MpServer', x=-312.48, y=68.00, z=147.14], EntityChicken['Chicken'/576, l='MpServer', x=-318.20, y=68.00, z=147.20], EntityChicken['Chicken'/577, l='MpServer', x=-316.50, y=69.00, z=144.50], EntityChicken['Chicken'/578, l='MpServer', x=-316.50, y=69.00, z=144.50], EntityBat['Bat'/715, l='MpServer', x=-264.46, y=15.79, z=156.89], EntitySquid['Squid'/716, l='MpServer', x=-264.34, y=59.40, z=198.84], EntitySquid['Squid'/717, l='MpServer', x=-269.70, y=60.54, z=200.87], EntityChicken['Chicken'/857, l='MpServer', x=-229.69, y=63.00, z=172.51], EntityChicken['Chicken'/858, l='MpServer', x=-228.47, y=63.00, z=172.63], EntityChicken['Chicken'/859, l='MpServer', x=-229.22, y=63.00, z=173.19], EntityChicken['Chicken'/860, l='MpServer', x=-228.50, y=64.00, z=169.35], EntityFallingBlock['Falling Block'/350, l='MpServer', x=-367.50, y=14.21, z=183.50], EntityFallingBlock['Falling Block'/351, l='MpServer', x=-366.50, y=14.21, z=183.50], EntityFallingBlock['Falling Block'/352, l='MpServer', x=-367.50, y=14.21, z=182.50], EntitySquid['Squid'/618, l='MpServer', x=-289.09, y=62.03, z=213.22], EntitySquid['Squid'/619, l='MpServer', x=-293.81, y=61.51, z=211.86], EntityFallingBlock['Falling Block'/236, l='MpServer', x=-395.50, y=19.34, z=203.50], EntitySquid['Squid'/620, l='MpServer', x=-290.86, y=62.61, z=215.56], EntityWitch['Witch'/2028, l='MpServer', x=-259.50, y=15.00, z=157.50], EntityWitch['Witch'/2029, l='MpServer', x=-254.50, y=15.00, z=156.50], EntityWitch['Witch'/2030, l='MpServer', x=-257.50, y=15.00, z=158.50], EntityFallingBlock['Falling Block'/249, l='MpServer', x=-369.50, y=15.34, z=182.50], EntityFallingBlock['Falling Block'/250, l='MpServer', x=-369.50, y=15.34, z=183.50], EntityFallingBlock['Falling Block'/251, l='MpServer', x=-368.50, y=15.34, z=182.50], EntityFallingBlock['Falling Block'/252, l='MpServer', x=-368.50, y=15.34, z=183.50], EntityFallingBlock['Falling Block'/253, l='MpServer', x=-370.50, y=15.34, z=182.50], EntityFallingBlock['Falling Block'/254, l='MpServer', x=-370.50, y=15.34, z=183.50], EntityFallingBlock['Falling Block'/255, l='MpServer', x=-371.50, y=15.34, z=182.50]]
    Retry entities: 0 total; []
    Server brand: vanilla
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:448)
    at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:2929)
    at net.minecraft.client.Minecraft.run(Minecraft.java:424)
    at net.minecraft.client.main.Main.main(Main.java:120)

-- System Details --
Details:
    Minecraft Version: 1.10
    Wurst Client Version: 4.3 (latest: 4.3)
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_77, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 143174360 bytes (136 MB) / 343220224 bytes (327 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    Launched Version: 1.10.X Wurst Client
    LWJGL: 2.9.4
    OpenGL: Intel(R) HD Graphics GL version 4.0.0 - Build 10.18.10.4358, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Very likely; Jar signature invalidated
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Intel(R) Pentium(R) CPU G2030 @ 3.00GHz
```

**Comment by Alexander01998** [comment]
Please answer my questions in https://github.com/Wurst-Imperium/Wurst-Client-Bugs/issues/221#issuecomment-246728704.
