### ISSUE TITLE
Aiming with throwable things

### ISSUE THREAD

**Issue by JustLimited** [Wurst-Imperium/Wurst-Client-Bugs#25]
#### Description of the Bug
i wanted to shoot with the bow in multiplayer and it shoots to a different location than i wat it to but in singleplayer it works help me

#### How to Reproduce the Bug
it needs to shoot like a proper bow

#### Other Information
- Wurst Client version: 3.1
- Operating system: Windows

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Alexander01998** [comment]
You have Derp, Headless or a similar mod enabled that messes with the direction that you're looking at. You must disable those mods before shooting with a bow.
