### ISSUE TITLE
Fullbright issue.

### ISSUE THREAD

**Issue by SeniorTaco** [Wurst-Imperium/Wurst-Client-Bugs#259]
Hi, after I was finished using the fullbright cheat, I logged of to play legit again. When I logged back on, (on my non-wurst profile) I noticed that things that should have been dark are still bright, just like if I had the full bright cheat on. The wurst version I was running at the time was for minecraft 1.9. I tried different versions of mc to see if it would fix its self, but that didn't help. Do you have any ideas?

Here is a screen shot of it:

(https://cloud.githubusercontent.com/assets/23463754/20284969/7f4084c8-aa8d-11e6-9b16-3205f25bbeb1.png)

Notice i am running 1.6.4. This proves that changing versions doesn't help.

**Comment by GlitchHead** [comment]
just adjust the brightness option in minecraft and it will fix itself.
