### ISSUE TITLE
Hitting invisible entities (MC 1.10-1.11)

### ISSUE THREAD

**Issue by AAgamesnl** [Wurst-Imperium/Wurst-Client-Bugs#262]
#### Description of the Bug
i was hacking on a server that has the plugin antiaura installed and i have set the target to only players
but wen i use killaura it hits the invisible entity's !!!!!
#### How to Reproduce the Bug
just enable killaura target to players and you will see that you are hit the flying entity above you!

#### Other Information
- Wurst Client version: 5.1
- Operating system: 10 64x

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by GlitchHead** [comment]
Can confirm on wurst 5.0 the client seems to completely ignore the "Attack invisible players" option in target settings or in killaura settings even if you have everything disabled it will still attack invisible players

**Comment by AAgamesnl** [comment]
not fixed in wurst 5.1 :((((( 
still hittiing invisible entities

**Comment by AAgamesnl** [comment]
or players
