### ISSUE TITLE
TriggerBot is nonfunctional (MC 1.10)

### ISSUE THREAD

**Issue by Beezlesnort** [Wurst-Imperium/Wurst-Client-Bugs#263]
#### Description of the Bug
I use triggerbot when sitting at mob grinders to kill them as they spawn.  It works great, and I can AFK while getting that sweet sweet XP.  But after upgrading to 4.5 or 4.6, it no longer works.  It still works on version 4.4.

#### How to Reproduce the Bug
Enable triggerbot.  Walk up to a mob, and put the crosshair on it.  It should start attacking the mob, but doesn't.

I checked the settings under "Target".  I have "Monsters" checked, everything else unchecked.

#### Other Information
- Wurst Client version: 4.5 & 4.6
- Operating system: Windows 10 64-bit

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by AAgamesnl** [comment]
there is something going on with the targed settings 

its also with killaura

you are automaticly hiytting invisble entiy's :(
