### ISSUE TITLE
.goto and .path with ladders missing at the top or bottom

### ISSUE THREAD

**Issue by TheIonosphere** [Wurst-Imperium/Wurst-Client-Bugs#264]
#### Description of the Bug
.path and .goto do not recognise viable paths where a ladder at the top or bottom is missing.

A player can climb a ladder at head height, without needing one at the level of their feet.

A player can also stand on top of a ladder and jump onto a block above, so ladders at the top can be missing.

Neither case is taken into account by the commands so it says there is no path when these ones actually exist.
![2016-11-19_01 32 22](https://cloud.githubusercontent.com/assets/13650573/20451978/16a0b208-adf8-11e6-8dbe-4d9da370567e.png)

#### How to Reproduce the Bug
Try to use .path or .goto to reach a destination accessible only by ladders, with one missing at either the top or the bottom.

#### Other Information
- Wurst Client version: 4.6 (released Friday 18/11/2016)
- Operating system: Windows 8.1

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Alexander01998** [comment]
Fixed.
