### ISSUE TITLE
Can't connect Spigot 1.9.4

### ISSUE THREAD

**Issue by vovanre** [Wurst-Imperium/Wurst-Client-Bugs#27]
#### Description of the Bug
Can't connect to Spigot 1.9.4
![bug](http://joxi.ru/BA0ddGjFB87O7A?d=1)

#### How to Reproduce the Bug
1. Connect to server - Spigot 1.9.4
2. ...

#### Other Information
- Wurst Client 3.2 (Last commit)
- Operating system: 
Windows 7 x64
---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by GlitchHead** [comment]
I seem to just be getting a outdated client error when connecting to any spigot 1.9.4 server.

**Comment by vovanre** [comment]
Wurst client can't connect to 1.9.4, to many protocol differences. For example:
1.9: http://wiki.vg/index.php?title=Protocol&oldid=7617#Chunk_Data
1.9.4: http://wiki.vg/Protocol#Chunk_Data

**Comment by mcccs** [comment]
I can confirm this, but I'm sure the same thing for BungeeCord with 1.9.1/2/3/4.

**Comment by 37QhaP** [comment]
+ I can confirm this too!
+ Also if you try to connect with 1.9.3/1.9.4 version in 1.9.x server you will get this error:
![67nj368n3](https://cloud.githubusercontent.com/assets/19511214/15457748/fcbd92ae-2097-11e6-981b-31edca3a1c56.png)

**Comment by Beezlesnort** [comment]
More info.  When connecting to a vanilla Minecraft server (jar direct from Mojang, unmodified), it says:

Internal Exception: io.netty.handler.codec.DecoderException:
com.google.gson.JsonSyntaxException:
com.google.gson.stream.MalformedJsonException: Use
JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1

**Comment by ehhthing** [comment]
I can confirm this, this also happens on paper servers.

**Comment by tspierer2** [comment]
I am having the same error. But I can't seem to connect to anything with 1.9.4 button switched on.
http://prntscr.com/be1y3k

**Comment by mcccs** [comment]
Never mind about 1.9. 1.19 just launched.

**Comment by ThaRealMrGong** [comment]
The issue is that wurst isn't handling the packets correctly. Instead of simply reading excess bytes, actually look at the protocol specification (http://wiki.vg/Protocol_History) and change appropriate ByteBuf reads to read the right values. I was able to allow my client to join 1.9, 1.9.2, 1.9.4, and 1.10 (doesn't allow spawning of polar bears).

**Comment by ThisTestUser** [comment]
For 1.9.4, you need to do more than just change bytes...

**Comment by ThaRealMrGong** [comment]
Yes, for 1.9.4 you have an additional list of tile entities in the chunk data packet that you need to read and process when the packet comes in. Its really not that hard, took maybe 3 days to finish

**Comment by ThisTestUser** [comment]
That's not what I mean, I mean the packet ID changes.

**Comment by ThaRealMrGong** [comment]
Packet data and id are two different things. Yeah swapping the ids lets you log in, but there are different data types (var int, byte, integer, etc) that are being sent differently than prior versions

**Comment by ThisTestUser** [comment]
Have you managed to swap ids in game?

**Comment by ThaRealMrGong** [comment]
Yes, I made a 1.9 client compatible with all 1.9 versions and 1.10

**Comment by ThisTestUser** [comment]
Without logging out though?

**Comment by ThaRealMrGong** [comment]
What do you mean?

**Comment by ThisTestUser** [comment]
If you could switch a client's version without restarting it.

**Comment by ThaRealMrGong** [comment]
Eh, the clients version isn't switched. The client doesn't even have a button to choose your server version, it uses the protocol number the server sends you when you ping the server to determine how to modify your packets.

**Comment by mcccs** [comment]
> Eh, the clients version isn't switched. The client doesn't even have a button to choose your server version, it uses the protocol number the server sends you when you ping the server to determine how to modify your packets.

Nice!

**Comment by ThaRealMrGong** [comment]
https://github.com/MylesIsCool/ViaVersion/tree/master/src/main/java/us/myles/ViaVersion/protocols

You can also have a look at this for some information on stuff that has changed.
