### ISSUE TITLE
Game Crashes when you try to play a map or server

### ISSUE THREAD

**Issue by MinecraftPro12345** [Wurst-Imperium/Wurst-Client-Bugs#287]
#### What Minecraft versions are affected by this bug?

- [ ] MC 1.11
- [x] MC 1.10
- [ ] MC 1.9
- [ ] MC 1.8

#### What operating systems are affected by this bug?

- [x] Windows 10
- [ ] Windows 8 / 8.1
- [ ] Windows 7
- [ ] Linux
- [ ] Mac

**Comment by MinecraftPro12345** [comment]
Plz help me fix this I cant use my Hacked Client!!!

**Comment by iAshleysi** [comment]
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by iAshleysi** [comment]
everytime i  join a server it crashes with my wurst hacked 1.10 client
