### ISSUE TITLE
wurst 5.7 crashing after play in launcher

### ISSUE THREAD

**Issue by Lokiro67** [Wurst-Imperium/Wurst-Client-Bugs#298]
#### Briefly describe what is happening.
After installing the client, I fill out the profile correctly and I do play. Following its minecraft load and crash.

#### How can someone reliably cause this bug to happen?
i dont know i just installed the client and start the game after crash loading 

#### What Minecraft versions are affected by this bug?

- [X] MC 1.11
- [x] MC 1.10
- [ ] MC 1.9
- [ ] MC 1.8

#### What operating systems are affected by this bug?

- [X] Windows 10
- [ ] Windows 8 / 8.1
- [ ] Windows 7
- [ ] Linux
- [ ] Mac

#### Paste your crash report below.
No logs create just that in game output after crash

Completely ignored arguments: [--nativeLauncherVersion, 1148]
[18:31:50] [Client thread/INFO]: Setting user: ********
[18:31:51] [Client thread/INFO]: LWJGL Version: 2.9.4

**Comment by liach** [comment]
Are you using Java 8?

**Comment by Lokiro67** [comment]
yes im using java 8
