### ISSUE TITLE
How compile last version?

### ISSUE THREAD

**Issue by vovanre** [Wurst-Imperium/Wurst-Client-Bugs#30]
#### Description of the Bug
Can' compile last Wurst 1.9.x version.

#### How to Reproduce the Bug
1. Decompile Minecraft with MCPv9.24-beta1
2. Apply path from Wurst repo.
3. Add slick.jar
4. Add minecraft as source
5. Get too many error:
![](http://joxi.ru/Y2LjjQMfnWR17r?d=1)

#### Other Information
- Wurst Client version: 3.1
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Same.

**Comment by mcccs** [comment]
@vovanre Why did you close? We need a new tutorial.
