### ISSUE TITLE
NameProtect doesn't work

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst-Client-Bugs#32]
#### Description of the Bug
Nothing happens when I enable NameProtect.

#### How to Reproduce the Bug
Enable it.

#### Other Information
- Wurst Client version: 3.1
- Operating system: MAC OS X 11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by 37QhaP** [comment]
A remind: NameProtect is not changing your name for other player, only for you.!
This feature created for YouTube videos, in case you don't want to show your real name to world. etc...

Also, i think you can change the name with a command. Search on NameProtect description..!

**Comment by mcccs** [comment]
I know, I didn't mean that.
![www gifcreator me_dgygxd](https://cloud.githubusercontent.com/assets/11584045/15471992/8af4501c-2101-11e6-9c1f-d9da4f9088d0.gif)

I mean, it is not working on client side too.

**Comment by javacoolme** [comment]
Yeah, same thing happening here, PLZ FIX!
