### ISSUE TITLE
Clickgui 1.8 problem

### ISSUE THREAD

**Issue by Killergor** [Wurst-Imperium/Wurst-Client-Bugs#33]
#### Description of the Bug
When I try to open with rshift or other keybinds in 1.8 and it does nothing

#### How to Reproduce the Bug
I have wurst 1.9 and in 1.8 it does this bug for me, just open the clickgui in 1.8

#### Other Information
- Wurst Client version: 2.21
- Operating system: Mac software: Yosemite

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Press "Reset Keybinds"
![screen shot 2016-05-16 at 17 29 34](https://cloud.githubusercontent.com/assets/11584045/15292454/d64d64a2-1b8b-11e6-946b-a9fc1c38e305.png)
