### ISSUE TITLE
Cant fly with elytra

### ISSUE THREAD

**Issue by GoodGuy217** [Wurst-Imperium/Wurst-Client-Bugs#42]
#### Description of the Bug
I cant fly with elyteas, i jumped down from hights and had elytras on but they didnt work and they worked without wurst.

#### How to Reproduce the Bug
you hve to just jump down from hights with elytras on. 

#### Other Information
- Wurst Client version: 3.2
- Operating system: windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Which mods are enabled?

**Comment by GoodGuy217** [comment]
tracer,regen and chest esp

2016-05-20 19:32 GMT+03:00 MCCCS <notifications@github.com>:

**Comment by mcccs** [comment]
Working fine for me.

**Comment by mcccs** [comment]
> you hve to just jump down from hights with elytras on.

This not how you fly with Elytra. You forgot to press jump while you're mid-air.
