### ISSUE TITLE
Auto Walk Issue

### ISSUE THREAD

**Issue by 37QhaP** [Wurst-Imperium/Wurst-Client-Bugs#47]
#### Description of the Bug
If im not wrong auto walk should stop when the player opens invertory or a chest.
I expected when i opened the chest, stop walking until i exit it.. Also we have the menu walk to take care of this (invertory and chest moving)..

#### How to Reproduce the Bug
If you open chest or invertory with auto walk on, the player will keep going.

#### Other Information
- Wurst Client version: 3.2
- Operating system: Windows 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
This is an intended feature, but this repository is only for bugs.

**Comment by 37QhaP** [comment]
I already know what should i share here, but thanks.
I see this as an issue 'bug' or incomplete code, so i reported it.
Our friend Alexander should take care and add some 'controls' and don't let the mod's do whatever they want. ( Im not talking only for Auto-Walk. A lot mods have 'incomplete code' and this is not Alexanders fault. If we help him and tell him that here is 'missing' something, then he will think about it. )

Cheers to Alexander! Keep the good work.!

**Comment by mcccs** [comment]
We need a checkbox for that. Some users won't like this idea but many will like too.

**Comment by 37QhaP** [comment]
I agree.
A more advanced 'setting-feature-control' about some mods, will be great.

Or just a better compile in the mods.
e.g. In the description of Auto-Walk, a box that say about invertory moving if you enable menu walk.

( I believe that this is an improvement, because some features is that give you the 'undetectable identity'. )

**Comment by mcccs** [comment]
But still, this isn't allowed by the first rule of [Contributing Guidelines](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md).

**Comment by 37QhaP** [comment]
We talked about this in comments and no in the issue that i created.
I don't know what Alexander write in the code so idk if this is a bug or incomplete code.
In this case i reported this as a bug and not a suggestion..

+ ( Also we have the menu walk to take care of this (invertory and chest moving).. ) <- That was only a clarification to make Alexander think about it.!

+ Also let me know where i can write suggestions!!
