### ISSUE TITLE
Can't join any servers

### ISSUE THREAD

**Issue by Aggronite** [Wurst-Imperium/Wurst-Client-Bugs#48]
#### Description of the Bug
So, when I try to join any server with Wurst, i get THIS message: InternalExeption: io.netty.codec.DecoderExeption:java.lang.IndexOutOfBounds: readerIndex(18) + length(1) exceeds writerIndex(18): UnpooledHeapByteBuf(ridx: 18, widx: 18, cap: 18)  This doesn't happen with Vanilla, only Wurst.

#### How to Reproduce the Bug
I have no idea, except joining a server. I haven't messed with anything, or done anything special.
#### Other Information
- Wurst Client version: 3.2
- Operating system: Windows 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by 37QhaP** [comment]
What protection programs you using?
What is the version of server you try to join?
Also, did you tried to change the versions? (in 1.9.4 servers wurst have some problems)

**Comment by mcccs** [comment]
For short: Change the version to 1.9 and if it doesn't work, wait for an update.

**Comment by broese** [comment]
Same issue here - Wurst in 1.9.2 mode cannot join Vanilla 1.9.2 server, and in 1.9.3/4 mode it cannot join Vanilla 1.9.4 server, throwing the error message in OP post
