### ISSUE TITLE
Open to LAN button opens Wurst Options

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst-Client-Bugs#5]
#### Description of the Bug
The "Open to LAN" button opens the Wurst Options screen instead of the Open To LAN screen.

#### How to Reproduce the Bug
Click the "Open to LAN" button.

#### Other Information
- Wurst Client version: 3.0
- Operating system: Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThisTestUser** [comment]
You forgot the break; at the end of Open to Lan.
