### ISSUE TITLE
X-ray Block Removing Doesn't Work

### ISSUE THREAD

**Issue by killer33778** [Wurst-Imperium/Wurst-Client-Bugs#50]
#### Description of the Bug
What I was trying to do was remove a block from X-ray on 1.9 WURST hacked client. Well it didn't work so I tried a couple more times and still didn't work. What happened instead was that the block wouldn't go away and well yea. I was on an online Mine Craft server and did X-ray and i saw "Glass Pane" so I tried to remove it from my X-ray and it wouldn't remove. That was my first encounter with this bug but didn't report it cause I thought it was my computer. So a few days later I go back onto Mine Craft and play single-player and wanted coal to go away and i tried the, .xray remove name coal, and it said "Wurst ERROR Block 0 ("coal") is not in your X-ray blocks list" And I got confused and then realized it wasn't fixed. So I reported this bug.

#### How to Reproduce the Bug
.xray remove name [name of block]

#### Other Information
- Wurst Client version: 1.9
- Operating system: Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
> Wurst Client version: 1.9

Did you mean 3.1?
