### ISSUE TITLE
Killaura stops working when you go to freecam mode

### ISSUE THREAD

**Issue by GravelCZLP** [Wurst-Imperium/Wurst-Client-Bugs#51]
#### Description of the Bug
When you enable killaura and you will go to freecam mode killaura stops hiiting entities. 

#### How to Reproduce the Bug
This bug happens when you enable killaura and you will go to freecam mode. killaura stops working and works only there where you are in freecam. when you exit the frrecam killaura does not hitting entitys until you restart killaura or new entity comes to your killauras range.

#### Other Information
- Wurst Client version: 3.2 for Minecraft 1.9
- Operating system: Microsoft Windows 10 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Alexander01998** [comment]
That's not a bug. The player standing at the position where you activated Freecam is a fake player and cannot hit entities. The real player is being moved with the camera and teleported back to its old position once you disable Freecam.
