### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by JarettH** [Wurst-Imperium/Wurst-Client-Bugs#52]
IT keep crashing, whenever I use it on the server Desteria I crash 

Long on to server Desteria
#### Other Information
- Wurst Client version: 3.2
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.
[Crash.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/281183/Crash.txt)

**Comment by 37QhaP** [comment]
Desteria is a lot of laggy server..
