### ISSUE TITLE
No place to suggest features publicly

### ISSUE THREAD

**Issue by pokeball99** [Wurst-Imperium/Wurst-Client-Bugs#53]
#### Description of the Bug
Bug: no good place to suggest features publicly
Solution: make an "Wurst-Client-Features" repo
#### How to Reproduce the Bug
find a lack of places to suggest features

#### Other Information
- Wurst Client version: all
- Operating system: any

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
#### Description of the Abusement

Spammers spam the issue sugestion repository.

#### How to fix the Abusement

Don't have a suggestion repository

#### Other Information

- People: Spammers
- Evidence: Old issues

----
I have read and understood the Bug Tracker Rules before posting this bug report and filled out the template above with the correct information.

**Comment by pokeball99** [comment]
this is somewhat of a joke, but 1. i'm serious about there being an need about an suggestion "tracker", and 2. what other issues have their been about this? none that still exist anymore

**Comment by Alexander01998** [comment]
> 1. **Only submit bug reports, nothing else!**  
> Do not suggest features or ask questions here! This repository is for bug reports only.
> 
> Violating any of these rules can get you banned from all Wurst-Imperium repositories. You have been warned!

I was **not** kidding when I said that.
