### ISSUE TITLE
Java Exception Error - UnsupportedClassVersion

### ISSUE THREAD

**Issue by Alkaris** [Wurst-Imperium/Wurst-Client-Bugs#54]
#### Description of the Bug
Unsupported Class Version error in Java

![shutter_2016-05-05-27-16__22_06_15_pm](https://cloud.githubusercontent.com/assets/6682988/15608208/a44ba9cc-245b-11e6-803a-65604911e1f7.png)

#### How to Reproduce the Bug
Install Wurst 3.2 for 1.9.4 and select for profile you want to use then hit Play.

#### Other Information
- Wurst Client version: 3.2
- Operating system: Linux
- Java version: OpenJDK 1.7.0_107

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by liach** [comment]
Please use Java8

**Comment by mcccs** [comment]
```
$ sudo apt-get install openjdk-8-jre
```

**Comment by mcccs** [comment]
```
$ sudo apt-get install openjdk-8-jre
```
Did it work? If yes: 
![](https://cloud.githubusercontent.com/assets/11584045/16191674/1c837506-36ee-11e6-8600-895d18d35c5d.png)
