### ISSUE TITLE
PotionSaver is broken

### ISSUE THREAD

**Issue by ghost** [Wurst-Imperium/Wurst-Client-Bugs#57]
#### Description of the Bug
Not working anymore.

#### How to Reproduce the Bug
Enable it

#### Other Information
- Wurst Client version: Wurst Client v3.2
- Operating system: MAC OS X 11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by ThaRealMrGong** [comment]
Patched in 1.9

**Comment by mcccs** [comment]
Then remove it?

**Comment by ThaRealMrGong** [comment]
How would I do that? I'm a lowly commentator :P

**Comment by mcccs** [comment]
I can open a Pull Request for that, and I did it for Session Stealer, but @Alexander01998 didn't accept it's not working.

**Comment by ThisTestUser** [comment]
There are a lot of other mods patched too...
https://github.com/ThisTestUser/Docs/blob/master/ClientStuff.md
