### ISSUE TITLE
Hiden names of mods in guide [ctrl]

### ISSUE THREAD

**Issue by sacredgreed** [Wurst-Imperium/Wurst-Client-Bugs#59]
![mc](https://cloud.githubusercontent.com/assets/14905138/15631319/f3c3e8ee-2563-11e6-85a3-62d1fcca5937.PNG)
#### Description of the Bug
In my hack menu i cant see names of mods. I dont know why, i tried to change language but it doesnt help me.

#### How to Reproduce the Bug
Please help me resolve the problem, thank you

#### Other Information
- Wurst Client version: 3.2
- Operating system: win 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Please answer those:

1) Did you modify Wurst Jar?
2) Does that server have a custom ResourcePack? (Or do you use a resourcepack that changes font?)
3) Since when is the hack menu (it's called Navigator) broken?
4) Do you have Segoe installed? (It comes pre-installed)
4A) Steps to check: Press Win Button + R , type the following: `%windir%\fonts` and press OK
Then look for Segoe or SegoeUI.

**Comment by sacredgreed** [comment]
1) no ididnt

2)server doesnt have and i have this pro in singleplayer too and others 
servers

3)this "eror" i have only in the latest version

4) i have segoe



maybe i must delete all files from older wurst version in .minecraft folder 
maybe there is problem i wil try check this way


---------- Původní zpráva ----------

Od: MCCCS <notifications@github.com>

Komu: Wurst-Imperium/Wurst-Client-Bugs <Wurst-Client-Bugs@noreply.github.com
>

Datum: 29. 5. 2016 10:44:56

Předmět: Re: [Wurst-Imperium/Wurst-Client-Bugs] Hiden names of mods in guide
[ctrl] (#59)


"

Please answer those:

1) Did you modify Wurst Jar?

2) Does that server have a custom ResourcePack? (Or do you use a 
resourcepack that changes font?)

3) Since when is the hack menu (it's called Navigator) broken?

4) Do you have Segoe installed? (It comes pre-installed)

4A) Steps to check: Press Win Button + R , type the following: %windir%\
fonts and press OK

Then look for Segoe or SegoeUI.

—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub
(https://github.com/Wurst-Imperium/Wurst-Client-Bugs/issues/59#issuecomment-222349599)
, or mute the thread
(https://github.com/notifications/unsubscribe/AONvMk_ZFixw9VhZTttYU9ZV4SWIjbSOks5qGVIEgaJpZM4IpNY_)
. 





"=

**Comment by sacredgreed** [comment]
i solve problem i deleted all files in .minecraft jar
i started shinigami luncher v3.1
and used newest wurtst 3.2 and its ok 
(files from older versions were the problem)

**Comment by mcccs** [comment]
![default](https://cloud.githubusercontent.com/assets/11584045/15676122/c03abb4c-274d-11e6-84f6-416e79708710.png)
