### ISSUE TITLE
Nuker kicks you from the server

### ISSUE THREAD

**Issue by Alexander01998** [Wurst-Imperium/Wurst-Client-Bugs#6]
#### Known facts
- It only happens on servers, singleplayer worlds are unaffected.
- Wurst version: 3.0 (also happened in the pre-releases)

#### Open questions
- Are SpeedNuker and Kaboom affected as well?
- Does this also happen in creative mode?

**Comment by mcccs** [comment]
Yes, Kaboom is affected too.

**Comment by Alexander01998** [comment]
> 1.8 is affected (I guess 1.7 is too.).

No way! This was definitely working in MC 1.8.X and 1.7.X.

**Comment by mcccs** [comment]
I guess I'll take a video tomorrow.

**Comment by Alexander01998** [comment]
> I'll take a video tomorrow.

I have literally griefed hundreds of servers with Nuker in MC 1.8 & 1.7. No video could ever prove that wrong.

**Comment by mcccs** [comment]
I mean I'll take a video of Kaboom. I'm 💯 % sure.

**Comment by Alexander01998** [comment]
> I mean I'll take a video of Kaboom. I'm  % sure.

I have also griefed dozens of servers with Kaboom.

**Comment by mcccs** [comment]
Just wait for my video, I completed 50% of it.

**Comment by mcccs** [comment]
Done: https://youtu.be/sPYtersgsFY

**Comment by mcccs** [comment]
Done: https://youtu.be/sPYtersgsFY

**Comment by vovanre** [comment]
Here is the server-side:

[13:52:20 INFO]: Player969 lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledHeapByteBuf(ridx: 1, widx: 1, cap: 1)

[13:52:20 INFO]: Player969 left the game.

**Comment by vovanre** [comment]
I found what is a bug, see [pull request](https://github.com/Wurst-Imperium/Wurst-Client-for-MC-1.9.X/pull/10)
