### ISSUE TITLE
Boat Fly Bug

### ISSUE THREAD

**Issue by 37QhaP** [Wurst-Imperium/Wurst-Client-Bugs#61]
#### Description of the Bug
Boat Fly Bug. BoatFly is not working if you are not flying over the water. *Anti-Cheats Servers
( An interesting thing is boat breaks lily pads, when where above them. )

+ What i expected to happen, is boat flies normally everywhere.

#### How to Reproduce the Bug
Enable BoatFly and try to pass water and go over blocks. Boat will break like i hit a block. Also when boat breaks, moves the player backwards. (Sometimes this not happening in real-time, but after some seconds.) Or if this is not happen. When i leave boat, is moving me backwards.

*I'll try to add some gifs the next days..

#### Other Information
- Wurst Client version: 3.2
- Operating system: Win7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Yep, NCP fixed it but still works on Mineplex Bridges and UHC.
