### ISSUE TITLE
Navigator Enabling

### ISSUE THREAD

**Issue by mcccs** [Wurst-Imperium/Wurst-Client-Bugs#67]
#### Description of the Bug
I don't know it is intended or not, but I don't think so.

When I click a Mod name in Navigator, it opens the description windows instead enabling it.

Same thing happens with commands.
#### How to Reproduce the Bug
Click a mod name in Navigator.

#### Other Information
- Wurst Client version: 3.3
- Operating system: MAC OS X EL CAPITAN 10.11.4

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by Alexander01998** [comment]
Working fine for me.

**Comment by mcccs** [comment]
Restart fixed it.
