### ISSUE TITLE
when i open a server than crash minecraft

### ISSUE THREAD

**Issue by yannismacke** [Wurst-Imperium/Wurst-Client-Bugs#69]
hello i have opened minecraft wurst 3.3 i go to the serverfinder and serche of server  than i open a server and the game crashes that is rally a pice of shit

**Comment by mcccs** [comment]
Weird. Try again, does it happen again?

**Comment by liach** [comment]
give crash report please

**Comment by Alexander01998** [comment]
And another one banned. :disappointed:
