### ISSUE TITLE
Cant open wurst

### ISSUE THREAD

**Issue by coco888** [Wurst-Imperium/Wurst-Client-Bugs#70]
Whenever i open up wurst i see the screen but i didnt get to the main menu and it just crahes...
Pls help me anyone

**Comment by mcccs** [comment]
https://www.wurst-client.tk/wiki/Java_8/

**Comment by mcccs** [comment]
@Alexander01998 What happened to [Java 8 Check](https://github.com/Wurst-Imperium/Wurst-Client-for-MC-1.9.X/blob/master/Wurst%20Client%20for%20MC%201.9.X/src/tk/wurst_client/java8check/Java8Checker.java)?

**Comment by Alexander01998** [comment]
> @Alexander01998 What happened to Java 8 Check?

I don't know. It's still there but it doesn't seem to work anymore.
