### ISSUE TITLE
Wurst crash if i join a server

### ISSUE THREAD

**Issue by AAgamesnl** [Wurst-Imperium/Wurst-Client-Bugs#74]
#### Description of the Bug
If i join a server the screen is white for 3 seconds and minecraft crash

#### How to Reproduce the Bug
[crash-2016-06-04_09.51.22-client.txt](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/files/298746/crash-2016-06-04_09.51.22-client.txt)

#### Other Information
- Wurst Client version:3.3
- Operating system: Windows 10 home 64-Bit

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.
Yes!

**Comment by Alexander01998** [comment]
It appears that you were playing on Hypixel when this crash occurred. Which one of the lobbies/games were you in?

**Comment by mcccs** [comment]
> Entity's Vehicle: ~~ERROR~~ NullPointerException: null

This happens to me when I play on Mineplex. I remember in an event (overpowered-games in Mineplex)
While we were in game waiting Lobby. 90% of players in that lobby crashed.

Minecraft's log said the same thing (Entity's Vehicle: ~~ERROR~~ NullPointerException: null) about Carl the Creeper.

**Comment by AAgamesnl** [comment]
no 
its crashing in all servers
mineplex
Hypixel
and cubecraftgames

i fixed this crash when i deleted the gui folder
in %appdata%/.minecraft/wurst

**Comment by mcccs** [comment]
Wait for the next update.
