### ISSUE TITLE
Presentation 404

### ISSUE THREAD

**Issue by rasmusolle** [Wurst-Imperium/Wurst-Client-Bugs#81]
#### Description of the Bug
On https://www.wurst-client.tk/wiki/Mods/Force_OP_(AuthMeCracker)/, the presentation tutorial gives a 404.

#### How to Reproduce the Bug
Go to https://www.wurst-client.tk/wiki/Mods/Force_OP_(AuthMeCracker)/

#### Other Information
- Wurst Client version: wurst-client.tk
- Operating system: Windows 7

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Thanks for the bug report!

**Comment by turbo614jr** [comment]
https://www.wurst-client.tk/bugs/

**Comment by turbo614jr** [comment]
my wurst mc when i go to a server it turns grey and crashes i cant use it it wont let me use a server
