### ISSUE TITLE
Can't Join Servers When Joining The Game Crashes

### ISSUE THREAD

**Issue by DisasterRunnner** [Wurst-Imperium/Wurst-Client-Bugs#89]
#### Description of the Bug
I tried To Join A Server And When It Finished Connecting to the server it said se binary not responding And It dosent say anything about it in the lancher and dosent creat a crsh report
#### How to Reproduce the Bug
-Open Minecraft Launcher
-release Wurst 
-open Multiplayer Tab
-join A Server
-and  Tada Your Game Crashed

#### Other Information
- Wurst Client version: 
- Operating system: 

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
1 Which server?
2 If it didn't create a crash report, it might be a laggy server or your RAM is not enough.
