### ISSUE TITLE
Report a bug screen not going away (MC 1.8)

### ISSUE THREAD

**Issue by Sippiboyz** [Wurst-Imperium/Wurst-Client-Bugs#91]
#### Description of the Bug
When the report a bug screen pops up, i cant make it go away even after pressing yes to exit the screen it just pops back up

#### How to Reproduce the Bug
I have no clue, all i did was press F which is my Killauralegit keybind IF this help here is the bug that its sending me and wont let me exit from: http://pastebin.com/wyCXUkWW

#### Other Information
- Wurst Client version:   2.21.2
- Operating system:  Windows 10

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
## Duplicate: #84 
![dupli](https://cloud.githubusercontent.com/assets/11584045/15435554/a30d6456-1ec5-11e6-83d3-787a691381ea.PNG)

**Comment by Sippiboyz** [comment]
that doesn't fix my problem? is there going to be an update? or is there a
way to fix it? thanks :D

**Comment by mcccs** [comment]
There's no way to fix it yet.

**Comment by Sippiboyz** [comment]
Ok thankyou very much

**Comment by mcccs** [comment]
And probably it won't be fixed, Wurst's developer is concentrated on Wurst 4.0 for MC 1.10.

**Comment by mcccs** [comment]
UPDATE: I posted
> And probably it won't be fixed, Wurst's developer is concentrated on Wurst 4.0 for MC 1.10.

this ^ by mistake. It'll be fixed one day.

**Comment by Sippiboyz** [comment]
Ok, thanks for the information i really appreciate it :D

**Comment by mcccs** [comment]
This bug happened on 2.11.2, which is an old version.
This bug will be fixed if you can prove that the same bug happens on Wurst 3.4.

**Comment by iAmelia** [comment]
This happened to me also, I can fix it.

1 - Log on to Wurst
2 - Log on to any 1.9 Server
3 - Press RShift as soon as you join
4 - Disable KALegit
5 - Enjoy!
:+1:
