### ISSUE TITLE
I CAN'T DELETE SOME COMMANDS

### ISSUE THREAD

**Issue by ZozaTech** [Wurst-Imperium/Wurst-Client-Bugs#97]
#### Description of the Bug
I wanted to be able to remove **all** of the commands, however it only lets me delete the commands on the valid commands list on the help list, but 'KillAura', 'Phase', and 'Sneak' are not on the help list, and I can't remove them

#### How to Reproduce the Bug
Use the command Killaura, phase or sneak 

#### Other Information
- Wurst Client version: v1.3.1

---

I have read and understood the [Bug Tracker Rules](https://github.com/Wurst-Imperium/Wurst-Client-Bugs/blob/master/.github/CONTRIBUTING.md) before posting this bug report and filled out the template above with the correct information.

**Comment by mcccs** [comment]
Download the latest version.
